In [1]:
#Importing Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import asarray
from sklearn.preprocessing import StandardScaler

In [5]:
ds=pd.read_excel(r"/content/drive/MyDrive/IBM PROJECT/DATASET/Crude Oil Prices Daily.xlsx") 

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
ds.head()

Date  Closing Value
0 1986-01-02          25.56
1 1986-01-03          26.00
2 1986-01-06          26.53
3 1986-01-07          25.85
4 1986-01-08          25.87

FEATURE SCALING

In [12]:
hd.describe()

NameError: ignored

In [9]:
x = ds.iloc[:, 1:3].values
print ("\nOriginal data values : \n",  x)
  
  
""" Handling the missing values """
  
from sklearn import preprocessing
  
""" MIN MAX SCALER """
  
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1))
  
# Scaled feature
x_after_min_max_scaler = min_max_scaler.fit_transform(x)
  
print ("\nAfter min max Scaling : \n", x_after_min_max_scaler)
  
  
""" Standardisation """
  
Standardisation = preprocessing.StandardScaler()
  
# Scaled feature
x_after_Standardisation = Standardisation.fit_transform(x)
  
print ("\nAfter Standardisation : \n", x_after_Standardisation)


Original data values : 
 [[25.56]
 [26.  ]
 [26.53]
 ...
 [73.05]
 [73.78]
 [73.93]]

After min max Scaling : 
 [[0.11335703]
 [0.11661484]
 [0.12053902]
 ...
 [0.46497853]
 [0.47038353]
 [0.47149415]]

After Standardisation : 
 [[-0.60550861]
 [-0.59065128]
 [-0.57275494]
 ...
 [ 0.99807057]
 [ 1.02272024]
 [ 1.02778524]]
